services:
  backend:
    build: ./backend
    container_name: geofence_backend
    restart: always # ADDED for robustness
    env_file:
      - .env
    command: node index.js
    networks: # ADDED
      - master_network
    # PORTS SECTION REMOVED. The master proxy will handle traffic.

  alerter:
    build: ./backend
    container_name: geofence_alerter
    restart: always
    env_file:
      - .env
    command: node alerter.js
    networks:
      - master_network
    depends_on:
      - backend

  frontend:
    build: ./frontend
    container_name: geofence_frontend
    restart: always # ADDED for robustness
    env_file:
      - .env
    depends_on:
      - backend
    networks: # ADDED
      - master_network
    # PORTS SECTION REMOVED. The master proxy will handle traffic.

# This section tells Docker Compose to use the 'master_network'
# that we already created manually.
networks:
  master_network:
    external: true